### ISSUE TITLE
Problème de sauvegarde

### ISSUE THREAD

**Issue by Frolipon** [goodenough/mosaico#101]
Hello,

J'ai un message d'erreur de sauvegarde lorsque je tente d'enregistrer un email à partir d'un template suivant sur la prod:
- société: Badsender
- template: _elle mastertemplate (badsender)_ ou _télé 7 jours mastertemplate (gvg)_

Quand je créé un email et que je tente de sauvegarder, j'ai un message d'erreur si l'email comprend une des sections suivantes:
bloc 3 colonnes ou bloc 4 colonnes
<img width="170" alt="fourcolumnsblock" src="https://cloud.githubusercontent.com/assets/14838636/23711460/454ca638-0420-11e7-9eeb-86447f6ab71c.png">
<img width="170" alt="threecolumnsblock" src="https://cloud.githubusercontent.com/assets/14838636/23711459/44fd9fb6-0420-11e7-9949-d326c3026f47.png">

Le problème est que le message d'erreur dans la console est assez succint:
![image](https://cloud.githubusercontent.com/assets/14838636/23711502/62cdab94-0420-11e7-8ade-daf4aa2b7340.png)

Il s'agit peut-être d'un problème dans le code de ces sections, mais je ne vois pas où. Pourrais-tu m'orienter sur la nature de l'erreur? Ou voir si l'erreur se situe ailleurs?

**Comment by Hiswe** [comment]
@Frolipon Il y a un problème pour l'enregistrement des données en base.
Je vais regarder de plus près ton template

Côté front la réponse du serveur est la suivante :

```json
{
  "name":"MongoError",
  "message":"The dotted field 'thirdColumnOptions.buttonVisible' in 'data.mainBlocks.blocks.0.thirdColumnOptions.buttonVisible' is not valid for storage.",
  "driver":true,
  "index":0,
  "code":57,
  "errmsg":"The dotted field 'thirdColumnOptions.buttonVisible' in 'data.mainBlocks.blocks.0.thirdColumnOptions.buttonVisible' is not valid for storage.",
  "status":500
}
```

Tout les logs de l'erreur côté serveur :

```
POST /editor/58c0de405e28cd0012d6be55
error handling 500
{ MongoError: The dotted field 'thirdColumnOptions.buttonVisible' in 'data.mainBlocks.blocks.3.thirdColumnOptions.buttonVisible' is not valid for storage.
    at Function.MongoError.create (/app/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/app/node_modules/mongodb/lib/utils.js:114:22)
    at /app/node_modules/mongodb/lib/collection.js:1049:67
    at /app/node_modules/mongodb-core/lib/connection/pool.js:455:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
 name: 'MongoError',
 message: 'The dotted field \'thirdColumnOptions.buttonVisible\' in \'data.mainBlocks.blocks.3.thirdColumnOptions.buttonVisible\' is not valid for storage.',
 [stack]: [Getter/Setter],
 driver: true,
 index: 0,
 code: 57,
 errmsg: 'The dotted field \'thirdColumnOptions.buttonVisible\' in \'data.mainBlocks.blocks.3.thirdColumnOptions.buttonVisible\' is not valid for storage.',
 status: 500 }
Trace: { MongoError: The dotted field 'thirdColumnOptions.buttonVisible' in 'data.mainBlocks.blocks.3.thirdColumnOptions.buttonVisible' is not valid for storage.
    at Function.MongoError.create (/app/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/app/node_modules/mongodb/lib/utils.js:114:22)
    at /app/node_modules/mongodb/lib/collection.js:1049:67
    at /app/node_modules/mongodb-core/lib/connection/pool.js:455:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
 name: 'MongoError',
 message: 'The dotted field \'thirdColumnOptions.buttonVisible\' in \'data.mainBlocks.blocks.3.thirdColumnOptions.buttonVisible\' is not valid for storage.',
 driver: true,
 index: 0,
 code: 57,
 errmsg: 'The dotted field \'thirdColumnOptions.buttonVisible\' in \'data.mainBlocks.blocks.3.thirdColumnOptions.buttonVisible\' is not valid for storage.',
 status: 500 }
   at /app/server/index.js:314:15
   at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
   at trim_prefix (/app/node_modules/express/lib/router/index.js:310:13)
   at /app/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)
» 9 Mar 2017 11:50:04.236  327 <158>1 2017-03-09T04:50:03.945021+00:00 heroku router - - at=info method=POST path="/editor/58c0de405e28cd0012d6be55" host=badsender.herokuapp.com request_id=f93d11d8-67db-41c7-8540-e0901da0ebac fwd="180.183.152.36" dyno=web.1 connect=0ms service=850ms status=500 bytes=619 protocol=http
   at next (/app/node_modules/express/lib/router/index.js:271:10)
   at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:67:12)
   at trim_prefix (/app/node_modules/express/lib/router/index.js:310:13)
   at /app/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)
   at next (/app/node_modules/express/lib/router/index.js:271:10)
   at next (/app/node_modules/express/lib/router/route.js:121:14)
   at process._tickDomainCallback (internal/process/next_tick.js:129:7)
POST - /editor/58c0de405e28cd0012d6be55 500
```

**Comment by Hiswe** [comment]
Sur le **dev** quand je crée un mailing à partir du template ELLE j'ai les messages suivant dans la console :

```
TODO EDITOR ignoring preheaderVisible property because it is not used by the template prop: preheaderVisible type: edit level: 1 template
editor.js:138 TODO EDITOR ignoring legalVisible property because it is not used by the template prop: legalVisible type: edit level: 1 template
editor.js:138 TODO EDITOR ignoring image.imageWidth property because it is not used by the template prop: imageWidth type: edit level: 2 coverArticleBlock
editor.js:138 TODO EDITOR ignoring backgroundColor property because it is not used by the template prop: backgroundColor type: styler level: 1 coverArticleBlock
editor.js:138 TODO EDITOR ignoring foregroundColor property because it is not used by the template prop: foregroundColor type: styler level: 1 coverArticleBlock
editor.js:138 TODO EDITOR ignoring titleStyle.size property because it is not used by the template prop: size type: styler level: 2 coverArticleBlock
editor.js:138 TODO EDITOR ignoring titleStyle.weight property because it is not used by the template prop: weight type: styler level: 2 coverArticleBlock
editor.js:138 TODO EDITOR ignoring titleStyle.alignement property because it is not used by the template prop: alignement type: styler level: 2 coverArticleBlock
editor.js:138 TODO EDITOR ignoring longTextStyle.spacer property because it is not used by the template prop: spacer type: styler level: 2 editoArticleBlock
editor.js:138 TODO EDITOR ignoring longTextStyle.lineheight property because it is not used by the template prop: lineheight type: styler level: 2 editoArticleBlock
editor.js:138 TODO EDITOR ignoring imageWidth property because it is not used by the template prop: imageWidth type: edit level: 1 singleImageBlock
editor.js:138 TODO EDITOR ignoring firstColumnOptions.imageVisible property because it is not used by the template prop: firstColumnOptions.imageVisible type: edit level: 1 threeColumnsBlock
editor.js:138 TODO EDITOR ignoring firstColumnOptions.copyVisible property because it is not used by the template prop: firstColumnOptions.copyVisible type: edit level: 1 threeColumnsBlock
editor.js:138 TODO EDITOR ignoring firstColumnOptions.titleVisible property because it is not used by the template prop: firstColumnOptions.titleVisible type: edit level: 1 threeColumnsBlock
editor.js:138 TODO EDITOR ignoring firstColumnOptions.buttonVisible property because it is not used by the template prop: firstColumnOptions.buttonVisible type: edit level: 1 threeColumnsBlock
editor.js:138 TODO EDITOR ignoring secondColumnOptions.imageVisible property because it is not used by the template prop: secondColumnOptions.imageVisible type: edit level: 1 threeColumnsBlock
editor.js:138 TODO EDITOR ignoring secondColumnOptions.copyVisible property because it is not used by the template prop: secondColumnOptions.copyVisible type: edit level: 1 threeColumnsBlock
editor.js:138 TODO EDITOR ignoring secondColumnOptions.titleVisible property because it is not used by the template prop: secondColumnOptions.titleVisible type: edit level: 1 threeColumnsBlock
editor.js:138 TODO EDITOR ignoring secondColumnOptions.buttonVisible property because it is not used by the template prop: secondColumnOptions.buttonVisible type: edit level: 1 threeColumnsBlock
editor.js:138 TODO EDITOR ignoring thirdColumnOptions.imageVisible property because it is not used by the template prop: thirdColumnOptions.imageVisible type: edit level: 1 threeColumnsBlock
editor.js:138 TODO EDITOR ignoring thirdColumnOptions.copyVisible property because it is not used by the template prop: thirdColumnOptions.copyVisible type: edit level: 1 threeColumnsBlock
editor.js:138 TODO EDITOR ignoring thirdColumnOptions.titleVisible property because it is not used by the template prop: thirdColumnOptions.titleVisible type: edit level: 1 threeColumnsBlock
editor.js:138 TODO EDITOR ignoring thirdColumnOptions.buttonVisible property because it is not used by the template prop: thirdColumnOptions.buttonVisible type: edit level: 1 threeColumnsBlock
editor.js:138 TODO EDITOR ignoring firstColumnOptions.image.imageWidth property because it is not used by the template prop: imageWidth type: edit level: 3 threeColumnsBlock
editor.js:138 TODO EDITOR ignoring firstColumnOptions.buttonLink.text property because it is not used by the template prop: text type: edit level: 3 threeColumnsBlock
editor.js:138 TODO EDITOR ignoring secondColumnOptions.image.imageWidth property because it is not used by the template prop: imageWidth type: edit level: 3 threeColumnsBlock
editor.js:138 TODO EDITOR ignoring secondColumnOptions.buttonLink.text property because it is not used by the template prop: text type: edit level: 3 threeColumnsBlock
editor.js:138 TODO EDITOR ignoring thirdColumnOptions.image.imageWidth property because it is not used by the template prop: imageWidth type: edit level: 3 threeColumnsBlock
editor.js:138 TODO EDITOR ignoring thirdColumnOptions.buttonLink.text property because it is not used by the template prop: text type: edit level: 3 threeColumnsBlock
editor.js:138 TODO EDITOR ignoring titleStyle property because it is not used by the template prop: titleStyle type: styler level: 1 threeColumnsBlock
editor.js:138 TODO EDITOR ignoring columnTitleStyle.weight property because it is not used by the template prop: weight type: styler level: 2 threeColumnsBlock
editor.js:138 TODO EDITOR ignoring columnLongTextStyle.spacer property because it is not used by the template prop: spacer type: styler level: 2 threeColumnsBlock
editor.js:138 TODO EDITOR ignoring columnLongTextStyle.lineheight property because it is not used by the template prop: lineheight type: styler level: 2 threeColumnsBlock
editor.js:138 TODO EDITOR ignoring firstColumnOptions.imageVisible property because it is not used by the template prop: firstColumnOptions.imageVisible type: edit level: 1 fourColumnsBlock
editor.js:138 TODO EDITOR ignoring firstColumnOptions.copyVisible property because it is not used by the template prop: firstColumnOptions.copyVisible type: edit level: 1 fourColumnsBlock
editor.js:138 TODO EDITOR ignoring secondColumnOptions.imageVisible property because it is not used by the template prop: secondColumnOptions.imageVisible type: edit level: 1 fourColumnsBlock
editor.js:138 TODO EDITOR ignoring secondColumnOptions.copyVisible property because it is not used by the template prop: secondColumnOptions.copyVisible type: edit level: 1 fourColumnsBlock
editor.js:138 TODO EDITOR ignoring thirdColumnOptions.imageVisible property because it is not used by the template prop: thirdColumnOptions.imageVisible type: edit level: 1 fourColumnsBlock
editor.js:138 TODO EDITOR ignoring thirdColumnOptions.copyVisible property because it is not used by the template prop: thirdColumnOptions.copyVisible type: edit level: 1 fourColumnsBlock
editor.js:138 TODO EDITOR ignoring fourthColumnOptions.imageVisible property because it is not used by the template prop: fourthColumnOptions.imageVisible type: edit level: 1 fourColumnsBlock
editor.js:138 TODO EDITOR ignoring fourthColumnOptions.copyVisible property because it is not used by the template prop: fourthColumnOptions.copyVisible type: edit level: 1 fourColumnsBlock
editor.js:138 TODO EDITOR ignoring firstColumnOptions.image.imageWidth property because it is not used by the template prop: imageWidth type: edit level: 3 fourColumnsBlock
editor.js:138 TODO EDITOR ignoring firstColumnOptions.buttonLink.text property because it is not used by the template prop: text type: edit level: 3 fourColumnsBlock
editor.js:138 TODO EDITOR ignoring secondColumnOptions.image.imageWidth property because it is not used by the template prop: imageWidth type: edit level: 3 fourColumnsBlock
editor.js:138 TODO EDITOR ignoring secondColumnOptions.buttonLink.text property because it is not used by the template prop: text type: edit level: 3 fourColumnsBlock
editor.js:138 TODO EDITOR ignoring thirdColumnOptions.image.imageWidth property because it is not used by the template prop: imageWidth type: edit level: 3 fourColumnsBlock
badsender-editor.js:14311 TODO EDITOR ignoring thirdColumnOptions.buttonLink.text property because it is not used by the template prop: text type: edit level: 3 fourColumnsBlock
badsender-editor.js:14311 TODO EDITOR ignoring fourthColumnOptions.image.imageWidth property because it is not used by the template prop: imageWidth type: edit level: 3 fourColumnsBlock
badsender-editor.js:14311 TODO EDITOR ignoring fourthColumnOptions.buttonLink.text property because it is not used by the template prop: text type: edit level: 3 fourColumnsBlock
badsender-editor.js:14311 TODO EDITOR ignoring titleStyle property because it is not used by the template prop: titleStyle type: styler level: 1 fourColumnsBlock
badsender-editor.js:14311 TODO EDITOR ignoring columnTitleStyle.weight property because it is not used by the template prop: weight type: styler level: 2 fourColumnsBlock
badsender-editor.js:14311 TODO EDITOR ignoring columnLongTextStyle.spacer property because it is not used by the template prop: spacer type: styler level: 2 fourColumnsBlock
badsender-editor.js:14311 TODO EDITOR ignoring columnLongTextStyle.lineheight property because it is not used by the template prop: lineheight type: styler level: 2 fourColumnsBlock
badsender-editor.js:14311 TODO EDITOR ignoring firstImage.imageWidth property because it is not used by the template prop: imageWidth type: edit level: 2 friseBlock
badsender-editor.js:14311 TODO EDITOR ignoring secondImage.imageWidth property because it is not used by the template prop: imageWidth type: edit level: 2 friseBlock
badsender-editor.js:14311 TODO EDITOR ignoring buttonLink.text property because it is not used by the template prop: text type: edit level: 2 ctaBlock
badsender-editor.js:14311 TODO EDITOR ignoring longTextStyle.spacer property because it is not used by the template prop: spacer type: styler level: 2 threeColumnsListBlock
badsender-editor.js:14311 TODO EDITOR ignoring longTextStyle.lineheight property because it is not used by the template prop: lineheight type: styler level: 2 threeColumnsListBlock
badsender-editor.js:14311 TODO EDITOR ignoring longTextStyle.alignement property because it is not used by the template prop: alignement type: styler level: 2 threeColumnsListBlock
badsender-editor.js:14311 TODO EDITOR ignoring buttonLink.text property because it is not used by the template prop: text type: edit level: 2 articleImageBlock
badsender-editor.js:14311 TODO EDITOR ignoring longTextStyle.spacer property because it is not used by the template prop: spacer type: styler level: 2 articleImageBlock
badsender-editor.js:14311 TODO EDITOR ignoring longTextStyle.lineheight property because it is not used by the template prop: lineheight type: styler level: 2 articleImageBlock
badsender-editor.js:14354 TODO WARN Missing label for object  theme
badsender-editor.js:14311 TODO EDITOR ignoring frameTheme property because it is not used by the template prop: frameTheme type: styler level: 0 theme
badsender-editor.js:14311 TODO EDITOR ignoring contentTheme.longTextStyle.spacer property because it is not used by the template prop: spacer type: styler level: 2 theme
badsender-editor.js:14311 TODO EDITOR ignoring contentTheme.longTextStyle.lineheight property because it is not used by the template prop: lineheight type: styler level: 2 theme
badsender-editor.js:14311 TODO EDITOR ignoring contentTheme.columnTitleStyle.weight property because it is not used by the template prop: weight type: styler level: 2 theme
badsender-editor.js:14311 TODO EDITOR ignoring contentTheme.columnLongTextStyle.spacer property because it is not used by the template prop: spacer type: styler level: 2 theme
badsender-editor.js:14311 TODO EDITOR ignoring contentTheme.columnLongTextStyle.lineheight property because it is not used by the template prop: lineheight type: styler level: 2 theme
badsender-editor.js:14311 TODO EDITOR ignoring bodyTheme property because it is not used by the template prop: bodyTheme type: styler level: 0 theme
badsender-editor.js:17609 generateEditors: 20.682ms
badsender-editor.js:13705 INFO Property  type missing in model, cloning from reference!
badsender-editor.js:13705 INFO Property  customStyle missing in model, cloning from reference!
badsender-editor.js:13705 INFO Property  subscriptionNumberVisible missing in model, cloning from reference!
badsender-editor.js:13705 INFO Property  preheaderVisible missing in model, cloning from reference!
badsender-editor.js:13705 INFO Property  legalVisible missing in model, cloning from reference!
badsender-editor.js:13705 INFO Property  engagementVisible missing in model, cloning from reference!
badsender-editor.js:13705 INFO Property  brandOption missing in model, cloning from reference!
badsender-editor.js:13705 INFO Property  ellePreheaderBlock missing in model, cloning from reference!
badsender-editor.js:13705 INFO Property  elletablePreheaderBlock missing in model, cloning from reference!
badsender-editor.js:13705 INFO Property  elledecoPreheaderBlock missing in model, cloning from reference!
badsender-editor.js:13705 INFO Property  elleLegalBlock missing in model, cloning from reference!
badsender-editor.js:13705 INFO Property  elltableLegalBlock missing in model, cloning from reference!
badsender-editor.js:13705 INFO Property  elledecoLegalBlock missing in model, cloning from reference!
badsender-editor.js:13705 INFO Property  mainBlocks missing in model, cloning from reference!
badsender-editor.js:13705 INFO Property  theme missing in model, cloning from reference!
```

**Comment by Hiswe** [comment]
@Frolipon la solution trouvée :

remplacer toutes les références du type :

```
firstColumnOptions.imageVisible
```

par 

```
firstColumnOptionsImageVisible
```


Pas de point en séparateur mais une majuscule

**Comment by Frolipon** [comment]
Comme vu sur Skype, le bug est résolu en dégommant le firstColumnOptions.imageVisible=true etc. des propriétés des blocs.

Ce serait un bug qui serait intéressant de remonter à Mosaico non?

**Comment by Hiswe** [comment]
Je ne pense pas que ce soit un bug.

Plutôt qu'il faille définir les valeurs par défaut d'un ensemble de widget dans cet ensemble et non pas là où il est instancé

**Comment by Hiswe** [comment]
@Frolipon J'ai mis à jour le template “témoin” avec une partie sur ce que tu veux

https://github.com/goodenough/mosaico/tree/february-2017/templates/sub-themes

**Comment by Frolipon** [comment]
Pour moi ça reste un bug, car il y a bien la possibilité dans les exemples du Versafix de définir pour un bloc ou pour une section une valeur par défaut, et pas seulement au niveau widget. Mais difficile à dire vu qu'on ne connaît pas les spec définies.

Pour info, le lien vers le template témoin ne fonctionne pas ;-)

**Comment by Hiswe** [comment]
@Frolipon Ah oui la branche a été supprimée

https://github.com/goodenough/mosaico/blob/master/templates/sub-themes/template-sub-themes.html

Si tu peux me donner l'endroit où c'est déclaré dans versafix je suis preneur :)

Pour pouvoir corriger ce problème d'enregistrement il existe bien une solution, mais il faudra passer par des script pour mettre à jour la DB. À voir donc

**Comment by Hiswe** [comment]
@Frolipon il y a d'autres choses à faire sur ce ticket ?

**Comment by Frolipon** [comment]
Nop, c'est fermé :-)
